// Blend In topic cards: 16 words each. s:1 = spicy-only.
const card = (topic, words, s) => ({ topic, words: words.split(',').map((w) => w.trim()), s: s ? 1 : 0 });

export const BLEND_CARDS = [
  card('Breakfast', 'Pancakes, Waffles, Bacon, Cereal, Toast, Omelette, Bagel, Muffin, Porridge, Croissant, Yogurt, Smoothie, French Toast, Hash Browns, Granola, Sausage'),
  card('Pizza Toppings', 'Pepperoni, Mushroom, Pineapple, Olives, Onion, Ham, Sausage, Anchovies, Jalapeño, Spinach, Bacon, Peppers, Chicken, Tomato, Basil, Extra Cheese'),
  card('At the Zoo', 'Lion, Giraffe, Penguin, Elephant, Gorilla, Zebra, Hippo, Flamingo, Kangaroo, Tiger, Panda, Crocodile, Koala, Rhino, Sloth, Meerkat'),
  card('Sports', 'Soccer, Basketball, Tennis, Golf, Baseball, Boxing, Hockey, Rugby, Swimming, Skiing, Surfing, Bowling, Wrestling, Volleyball, Cricket, Skateboarding'),
  card('Jobs', 'Doctor, Teacher, Chef, Pilot, Firefighter, Plumber, Lawyer, Dentist, Farmer, Astronaut, Barber, Magician, Lifeguard, Mechanic, Librarian, Clown'),
  card('Movie Genres', 'Horror, Comedy, Romance, Western, Musical, Sci-Fi, Action, Documentary, Fantasy, Thriller, Animation, Mystery, Superhero, War, Disaster, Heist'),
  card('In the Kitchen', 'Fridge, Toaster, Blender, Kettle, Microwave, Oven, Spatula, Whisk, Sink, Dishwasher, Cutting Board, Frying Pan, Colander, Ladle, Apron, Oven Mitt'),
  card('Superpowers', 'Flying, Invisibility, Super Strength, Telepathy, Time Travel, Teleporting, X-Ray Vision, Shapeshifting, Healing, Super Speed, Mind Control, Laser Eyes, Talking to Animals, Breathing Underwater, Freezing Time, Immortality'),
  card('Celebrations', "Christmas, Halloween, Thanksgiving, Easter, New Year's Eve, Valentine's Day, Birthday, Wedding, Graduation, Hanukkah, Diwali, St. Patrick's Day, Fourth of July, Baby Shower, Mother's Day, April Fools'"),
  card('Around Town', 'Bank, Library, Hospital, Gym, Bakery, Cinema, Post Office, Police Station, Supermarket, School, Museum, Laundromat, Pharmacy, Bowling Alley, Car Wash, Church'),
  card('Fast Food', 'Burger, Fries, Hot Dog, Taco, Fried Chicken, Nachos, Milkshake, Burrito, Onion Rings, Chicken Nuggets, Pizza Slice, Corn Dog, Sub Sandwich, Donut, Kebab, Fish and Chips'),
  card('At the Beach', 'Sandcastle, Seagull, Sunscreen, Surfboard, Towel, Umbrella, Crab, Seashell, Lifeguard, Waves, Swimsuit, Ice Cream, Flip-Flops, Sunburn, Volleyball, Pier'),
  card('Instruments', 'Guitar, Piano, Drums, Violin, Trumpet, Flute, Saxophone, Harp, Cello, Banjo, Ukulele, Accordion, Bagpipes, Harmonica, Tuba, Triangle'),
  card('Weather', 'Rain, Snow, Thunder, Lightning, Hail, Fog, Tornado, Hurricane, Rainbow, Sunshine, Drizzle, Blizzard, Heatwave, Frost, Wind, Sleet'),
  card('Fairy Tales', 'Cinderella, Snow White, Rapunzel, Pinocchio, Peter Pan, Hansel and Gretel, Red Riding Hood, Goldilocks, Sleeping Beauty, Jack and the Beanstalk, The Little Mermaid, Aladdin, Rumpelstiltskin, Three Little Pigs, Beauty and the Beast, The Frog Prince'),
  card('Clothing', 'Hoodie, Jeans, Sneakers, Scarf, Tuxedo, Pajamas, Raincoat, Sweater, Tie, Shorts, Socks, Hat, Gloves, Swimsuit, Dress, Overalls'),
  card('Vehicles', 'Bicycle, Helicopter, Submarine, Tractor, Motorcycle, Train, Rocket, Canoe, Bus, Taxi, Ambulance, Hot Air Balloon, Skateboard, Limo, Tank, Jet Ski'),
  card('Desserts', 'Cheesecake, Brownie, Ice Cream, Cupcake, Tiramisu, Apple Pie, Donut, Cookie, Pudding, Macaron, Churros, Crème Brûlée, Jelly, Banana Split, Fudge, Cannoli'),
  card('Body Parts', 'Elbow, Knee, Nose, Ear, Belly Button, Ankle, Eyebrow, Tongue, Thumb, Shoulder, Toe, Chin, Wrist, Neck, Knuckle, Armpit'),
  card('Tabletop Games', 'Chess, Monopoly, Scrabble, Poker, Uno, Checkers, Jenga, Twister, Battleship, Clue, Pictionary, Connect Four, Solitaire, Backgammon, Bingo, Dominoes'),
  card('In the Bathroom', 'Toothbrush, Shower, Mirror, Towel, Toilet, Soap, Shampoo, Bathtub, Razor, Plunger, Hairdryer, Floss, Rubber Duck, Scale, Toilet Paper, Bath Mat'),
  card('Fantasy Creatures', 'Dragon, Unicorn, Mermaid, Vampire, Werewolf, Ghost, Troll, Fairy, Zombie, Centaur, Goblin, Phoenix, Yeti, Wizard, Giant, Kraken'),
  card('School Days', 'Homework, Recess, Detention, Cafeteria, Principal, Locker, Exam, Field Trip, Backpack, Chalkboard, Yearbook, Prom, Gym Class, Report Card, School Bus, Science Fair'),
  card('Countries', 'Japan, Brazil, Italy, Canada, Mexico, Egypt, Australia, India, France, Germany, China, Spain, Greece, Ireland, Kenya, Iceland'),
  card('The Internet', 'Selfie, Meme, Hashtag, Emoji, Livestream, Influencer, Podcast, Viral Video, Unboxing, Troll, Likes, Spam, Wi-Fi, Password, Group Chat, Cat Video'),
  card('Camping', "Tent, Campfire, Marshmallows, Sleeping Bag, Flashlight, Bear, Mosquito, Canoe, Map, Hiking Boots, Compass, Lantern, S'mores, Ghost Story, Pocket Knife, Fishing Rod"),
  card('Weddings', 'Bride, Groom, Cake, Ring, Bouquet, Vows, Veil, First Dance, Best Man, DJ, Honeymoon, Speech, Tuxedo, Champagne, Confetti, Limo'),
  card('At the Office', 'Stapler, Printer, Meeting, Coffee Machine, Boss, Spreadsheet, Email, Cubicle, Water Cooler, Paperclip, Deadline, Intern, Lunch Break, Photocopier, Whiteboard, Promotion'),
  card('Hobbies', 'Knitting, Gardening, Painting, Fishing, Baking, Yoga, Gaming, Photography, Birdwatching, Pottery, Dancing, Reading, Karaoke, Woodworking, Juggling, Origami'),
  card('Outer Space', 'Moon, Sun, Mars, Astronaut, Black Hole, Comet, Galaxy, Rocket, Alien, Satellite, Meteor, Saturn, Telescope, Space Station, UFO, Star'),
  card('Party Time', 'Balloons, Cake, Piñata, DJ, Karaoke, Confetti, Party Hat, Punch, Candles, Presents, Dance Floor, Streamers, Party Games, Snacks, Invitations, Disco Ball'),
  card('Halloween', 'Pumpkin, Witch, Ghost, Skeleton, Candy, Costume, Bat, Spider, Mummy, Haunted House, Black Cat, Zombie, Broomstick, Cauldron, Vampire, Trick or Treat'),
  card('Pets', 'Dog, Cat, Hamster, Goldfish, Parrot, Rabbit, Turtle, Guinea Pig, Snake, Lizard, Ferret, Pony, Hedgehog, Chicken, Tarantula, Pig'),
  card('Things That Are Hot', 'Sun, Lava, Coffee, Oven, Chili Pepper, Fire, Sauna, Desert, Hot Sauce, Candle, Radiator, Toaster, Volcano, Kettle, Hair Straightener, Bonfire'),
  card('Superheroes', 'Batman, Superman, Spider-Man, Wonder Woman, Iron Man, Hulk, Thor, Black Panther, Captain America, Aquaman, The Flash, Wolverine, Black Widow, Deadpool, Robin, Catwoman'),
  card('Landmarks', 'Eiffel Tower, Great Wall, Statue of Liberty, Pyramids, Big Ben, Colosseum, Taj Mahal, Mount Rushmore, Stonehenge, Golden Gate Bridge, Leaning Tower of Pisa, Sydney Opera House, Machu Picchu, Hollywood Sign, Niagara Falls, Grand Canyon'),
  card('Drinks', 'Coffee, Tea, Lemonade, Milk, Orange Juice, Soda, Hot Chocolate, Smoothie, Water, Energy Drink, Milkshake, Iced Tea, Coconut Water, Kombucha, Root Beer, Sparkling Water'),
  card('Fruit', 'Apple, Banana, Mango, Pineapple, Strawberry, Watermelon, Grapes, Kiwi, Peach, Cherry, Lemon, Coconut, Pear, Blueberry, Orange, Avocado'),
  card('Things With Wheels', 'Car, Skateboard, Shopping Cart, Wheelchair, Stroller, Suitcase, Office Chair, Roller Skates, Wheelbarrow, Tricycle, Lawn Mower, Train, Bicycle, Scooter, Wagon, Tractor'),
  card('Cartoons', 'SpongeBob, The Simpsons, Scooby-Doo, Tom and Jerry, Pokémon, Bugs Bunny, Family Guy, Rick and Morty, Peppa Pig, Looney Tunes, South Park, Bluey, Mickey Mouse, Garfield, Futurama, Avatar'),
  card('Feelings', 'Happy, Angry, Jealous, Nervous, Bored, Excited, Embarrassed, Proud, Confused, Lonely, Grumpy, Hopeful, Guilty, Scared, Relaxed, Hangry'),
  card('In the Car', 'Steering Wheel, Seatbelt, Horn, Glovebox, Rearview Mirror, Radio, Air Freshener, Cupholder, Spare Tire, Windshield Wipers, Airbag, GPS, Sunroof, Brake Pedal, Trunk, Back Seat'),
  card('Game Characters', 'Mario, Pac-Man, Sonic, Pikachu, Link, Lara Croft, Master Chief, Kirby, Donkey Kong, Steve, Kratos, Crash Bandicoot, Yoshi, Luigi, Bowser, Tetris Block'),
  card('Famous Duos', 'Batman and Robin, Salt and Pepper, Romeo and Juliet, Peanut Butter and Jelly, Mario and Luigi, Tom and Jerry, Sherlock and Watson, Bonnie and Clyde, Mac and Cheese, Rick and Morty, Thelma and Louise, Lilo and Stitch, Shrek and Donkey, Bert and Ernie, Thunder and Lightning, Fish and Chips'),
  card('Things in a Wallet', 'Cash, Credit Card, Driver License, Receipt, Coins, Photo, Gift Card, Library Card, Business Card, Coffee Punch Card, Lottery Ticket, Bus Pass, Insurance Card, Stamp, Sticky Note, Key Card'),
  card('Under the Sea', 'Shark, Octopus, Jellyfish, Whale, Dolphin, Starfish, Seahorse, Clownfish, Sea Turtle, Lobster, Coral, Squid, Stingray, Pufferfish, Shipwreck, Seaweed'),
  card('Cocktail Hour', 'Margarita, Mojito, Martini, Piña Colada, Cosmopolitan, Old Fashioned, Daiquiri, Bloody Mary, Long Island Iced Tea, Sangria, Tequila Shot, Mimosa, Gin and Tonic, Whiskey Sour, Espresso Martini, Jägerbomb', 1),
  card('Date Night', 'Candlelight, Red Wine, Fancy Dinner, Movie, Flowers, First Kiss, Slow Dance, Shared Dessert, Blind Date, Netflix and Chill, Holding Hands, Cuddling, Dating App, Ghosting, Love Letter, Awkward Silence', 1),
  card('Bad Habits', 'Nail Biting, Snoring, Procrastinating, Gossiping, Swearing, Doomscrolling, Oversleeping, Knuckle Cracking, Littering, Lying, Interrupting, Impulse Buying, Junk Food, Being Late, Dirty Dishes, Leaving Read'),
  card('Hangover Cures', 'Greasy Breakfast, Water, Coffee, Aspirin, Sleep, Electrolytes, Hair of the Dog, Pickle Juice, Bacon Sandwich, Sunglasses, Burrito, Cold Shower, Banana, Sports Drink, Regret, Hashbrowns', 1),
  card('Things You Do in Bed', 'Sleep, Read, Snore, Binge TV, Eat Snacks, Scroll Phone, Cuddle, Dream, Toss and Turn, Nap, Breakfast in Bed, Pillow Fight, Talk in Sleep, Make the Bed, Hide Under Covers, Jump on It', 1),
];
