// Mind Dial spectrum cards: [left, right]. A third element of 1 = spicy-only.
export const DIAL_CARDS = [
  ['Cold', 'Hot'],
  ['Bad', 'Good'],
  ['Useless', 'Useful'],
  ['Underrated', 'Overrated'],
  ['Boring', 'Exciting'],
  ['Easy', 'Hard'],
  ['Unhealthy', 'Healthy'],
  ['Cheap', 'Expensive'],
  ['Sad song', 'Happy song'],
  ['Normal', 'Weird'],
  ['Soft', 'Hard'],
  ['Quiet', 'Loud'],
  ['Tiny', 'Huge'],
  ['Safe', 'Dangerous'],
  ['Rough', 'Smooth'],
  ['Forgettable', 'Unforgettable'],
  ['Villain', 'Hero'],
  ['Smells bad', 'Smells good'],
  ['Fictional', 'Real'],
  ['Old-fashioned', 'Modern'],
  ['Mild', 'Spicy'],
  ['Bad pet', 'Good pet'],
  ['Unlikable', 'Likable'],
  ['Lazy', 'Hardworking'],
  ['Casual', 'Formal'],
  ['Rare', 'Common'],
  ['Light', 'Heavy'],
  ['Mean', 'Nice'],
  ['Dry', 'Wet'],
  ['Low effort', 'High effort'],
  ['Mainstream', 'Niche'],
  ['Slow', 'Fast'],
  ['Introvert', 'Extrovert'],
  ['Weak', 'Strong'],
  ['Useless superpower', 'Amazing superpower'],
  ['Terrible gift', 'Perfect gift'],
  ['Worst day of the week', 'Best day of the week'],
  ['Bad movie', 'Great movie'],
  ['Fragile', 'Indestructible'],
  ['Ancient', 'Futuristic'],
  ['Childish', 'Mature'],
  ['Tastes bad', 'Tastes great'],
  ['Underpaid job', 'Overpaid job'],
  ['Harmless', 'Deadly'],
  ['Messy', 'Neat'],
  ['Plain', 'Fancy'],
  ['Scary', 'Comforting'],
  ['Unpopular', 'Popular'],
  ['Square', 'Round'],
  ['Bad habit', 'Good habit'],
  ['Hard to spell', 'Easy to spell'],
  ['Underdressed', 'Overdressed'],
  ['Worst pizza topping', 'Best pizza topping'],
  ['Cat person thing', 'Dog person thing'],
  ['Needs salt', 'Too salty'],
  ['Short-lived', 'Long-lasting'],
  ['Feels wrong', 'Feels right'],
  ['Hated in the 90s', 'Loved in the 90s'],
  ['Bad for a first date', 'Great for a first date'],
  ['Mildly annoying', 'Infuriating'],
  ['Kid-friendly', 'Adults only'],
  ['Trashy', 'Classy'],
  ['Unknown', 'World famous'],
  ['Underground', 'Mainstream'],
  ['Weird thing to own', 'Normal thing to own'],
  ['Worst Olympic sport', 'Best Olympic sport'],
  ['Bad name for a dog', 'Great name for a dog'],
  ['Unimportant', 'Important'],
  ['Tastes like chicken', "Doesn't taste like chicken"],
  ['Nature', 'Technology'],
  ['Easy to sing', 'Hard to sing'],
  ['Requires luck', 'Requires skill'],
  ['Calm', 'Chaotic'],
  ['Cute', 'Creepy'],
  ['Sweet', 'Bitter'],
  ['Hated chore', 'Fine chore'],
  ['Short', 'Tall'],
  ['Funny', 'Serious'],
  ['Bad advice', 'Good advice'],
  ['Unrealistic', 'Realistic'],
  ['Simple', 'Complicated'],
  ['Disgusting', 'Delicious'],
  ['Ugly', 'Beautiful'],
  ['Snack', 'Meal'],
  ['Cheap date', 'Expensive date'],
  ['Small talk', 'Deep conversation'],
  ['Throwaway', 'Heirloom'],
  ['Better hot', 'Better cold'],
  ['Mostly harmless animal', 'Terrifying animal'],
  ['Bad superhero name', 'Great superhero name'],
  ['Phone app', 'Real hobby'],
  ['Wholesome', 'Edgy'],
  ['Morning thing', 'Night thing'],
  ['Dorky', 'Cool'],
  ['Comfortable', 'Uncomfortable'],
  ['Overpriced', 'Worth every penny'],
  ['Loved by kids', 'Loved by grandparents'],
  ['Forgivable', 'Unforgivable'],
  ['Totally normal', 'Red flag'],
  ['Sober activity', 'Drunk activity', 1],
  ['Tame party', 'Wild party', 1],
  ['Not sexy', 'Sexy', 1],
  ['Innocent', 'Guilty', 1],
  ['Bad pickup line', 'Smooth pickup line', 1],
  ['Light drinker', 'Heavy drinker', 1],
];
