// Content for the face games. {A} / {B} are replaced with players' names.
const S = (t) => ({ t, s: 1 });

// Photobomb: two friends' faces become stickers; draw the scene around them.
export const PHOTO_SCENES = [
  '{A} and {B} on their first date',
  '{A} rescuing {B} from a dragon',
  "{A} and {B}'s wedding photo",
  '{A} and {B} robbing a bank',
  '{A} carrying {B} across the finish line',
  '{A} and {B} stranded on a desert island',
  '{A} as a mermaid and {B} as the fisherman',
  '{A} and {B} in a 90s boy band',
  '{A} and {B} as superheroes fighting a giant taco',
  '{A} and {B} riding a tandem bicycle',
  '{A} and {B} as the two halves of a horse costume',
  '{A} babysitting a giant baby {B}',
  '{A} and {B} on a reality dating show',
  '{A} and {B} trapped in a snow globe',
  '{A} and {B} as sushi rolls',
  "{A} as a giant monster attacking {B}'s city",
  '{A} and {B} at the prom',
  '{A} teaching {B} how to fly',
  '{A} and {B} as action figures, still in the box',
  '{A} and {B} arm wrestling',
  '{A} and {B} as astronauts on the moon',
  '{A} and {B} as two scoops of ice cream',
  '{A} walking {B} like a dog',
  "{A} and {B}'s cooking show disaster",
  '{A} and {B} as pirates fighting over treasure',
  '{A} and {B} running from the cops',
  '{A} and {B} as a two-headed dragon',
  '{A} and {B} in a family portrait from 1850',
  '{A} and {B} as jacked bodybuilders',
  '{A} and {B} screaming on a roller coaster',
  '{A} serenading {B} from under a balcony',
  '{A} and {B} as zombies at a birthday party',
  '{A} and {B} in a hot tub with a bear',
  '{A} and {B} stuck in an elevator',
  '{A} and {B} on the cover of a magazine',
  '{A} and {B} as pigeons fighting over a french fry',
  "{A} and {B}, the world's worst magicians",
  '{A} and {B} as cowboys at high noon',
  '{A} and {B} as garden gnomes',
  '{A} and {B} on the cover of a romance novel',
  '{A} and {B} trapped in a fishbowl',
  '{A} and {B} as rock stars smashing guitars',
  '{A} as a vampire and {B} as the snack',
  '{A} and {B} running a three-legged race',
  '{A} and {B} in a haunted house',
  '{A} and {B} as rival presidential candidates',
  '{A} and {B} as pro wrestlers',
  '{A} and {B} as babies in a stroller',
  '{A} and {B} on a seesaw',
  "{A} and {B} as a famous painting",
  '{A} and {B} as statues in a museum',
  '{A} and {B} as fruit in a fruit bowl',
  '{A} riding {B} into battle',
  '{A} and {B} as the last two people on Earth',
  '{A} and {B} in the world’s most awkward prom photo',
  S('{A} and {B} at their bachelor party'),
  S('{A} and {B} doing the walk of shame'),
  S('{A} and {B} in a cheesy 80s workout video'),
  S('{A} and {B} after a night in Vegas'),
  S('{A} and {B} in a steamy soap opera'),
];

// Zoom & Enhance: effect names the host can pick from.
export const ZOOM_EFFECTS = ['zoom', 'pixel', 'blur', 'strip', 'flip', 'swirl'];

// Most Wanted: starter ideas when someone is stuck.
export const CRIME_IDEAS = [
  'Eating the last slice and blaming the dog',
  'Replying "k" to a three-paragraph text',
  'Clapping when the plane lands',
  'Leaving one second on the microwave',
  'Spoiling the finale on purpose',
  'Stealing fries off every plate',
  'Wearing socks with sandals in public',
  'Starting a group chat and then going silent',
  'Putting an empty carton back in the fridge',
  'Faking a phone call to avoid small talk',
  'Saying "we should hang out" with no plan',
  'Talking during the movie',
  'Double-dipping the chips',
  'Never returning a borrowed hoodie',
  'Pretending to know the lyrics',
  'Liking a 3-year-old photo while stalking',
  'Unmuting just to say "you\'re on mute"',
  'Hoarding the good snacks',
  'Treating a yellow light as a challenge',
  'Being suspiciously good at karaoke',
];

// Pull a Face: make this face for the camera.
export const FACE_PROMPTS = [
  'Your face when the waiter brings someone else’s food',
  'You just stepped on a Lego',
  'Your best “blue steel” model face',
  'You just won the lottery',
  'You smelled something terrible',
  'Your face when someone says “we need to talk”',
  'You’re a villain revealing your evil plan',
  'You just saw a spider on your shoulder',
  'Your face when the WiFi goes out mid-game',
  'You’re pretending to like a gift',
  'The face you make at a baby',
  'You just remembered something embarrassing from 2011',
  'You’re trying to look innocent',
  'You heard a noise in the house at 3 a.m.',
  'You’re a sports fan whose team just lost',
  'Your face on a dating profile',
  'Your passport photo',
  'You’re a statue that just came to life',
  'You bit into a lemon',
  'You’re trying not to laugh at a funeral',
  'You just got away with it',
  'Your face when someone takes the last cookie',
  'Your dramatic soap opera reaction',
  'You’re the main character in a horror movie',
  S('Your face at 4 a.m. on a night out'),
  S('Your face when your ex walks in'),
];

// Split Decision: write the catch so the room splits 50/50.
export const SPLIT_TEMPLATES = [
  'You get a million dollars, but ____.',
  'You can fly, but ____.',
  'You’ll live to 150, but ____.',
  'You get free pizza for life, but ____.',
  'You can read minds, but ____.',
  'Your pet can talk, but ____.',
  'You never have to sleep again, but ____.',
  'You can teleport anywhere, but ____.',
  'You get your dream job, but ____.',
  'You can turn invisible, but ____.',
  'You can speak every language, but ____.',
  'You become world famous, but ____.',
  'You get a free mansion, but ____.',
  'You never age, but ____.',
  'You can time travel once, but ____.',
  'You get unlimited vacation days, but ____.',
  'You’ll meet your soulmate tomorrow, but ____.',
  'Every song you hum becomes a hit, but ____.',
  'You can pause time, but ____.',
  'You get superhuman strength, but ____.',
  'You can eat anything without gaining weight, but ____.',
  'You get a personal chef forever, but ____.',
  'You win every argument, but ____.',
  'You can breathe underwater, but ____.',
  'You can talk to animals, but ____.',
  'You get front-row seats to every concert, but ____.',
  'You’re the funniest person alive, but ____.',
  'You never get stuck in traffic again, but ____.',
  'You get a robot that does all your chores, but ____.',
  'You can relive any day of your life, but ____.',
  'You get to be on your favorite TV show, but ____.',
  'All your exes text you a sincere apology, but ____.',
  'You get $50 every time you sneeze, but ____.',
  'You can fly first class forever, but ____.',
  'You get the body of an Olympic athlete, but ____.',
  S('You get a free bar in your house, but ____.'),
  S('You’ll never have a hangover again, but ____.'),
];

// Pants on Fire: example statements to help people get started.
export const TRUTH_EXAMPLES = [
  'I once got stuck in a revolving door',
  'I can recite the alphabet backwards',
  'I have never seen a Star Wars movie',
  'I was chased by a goose as a kid',
  'I hate the taste of chocolate',
  'I won a dance competition',
];
