// Fib Factory facts. Every `a` is the true answer; `alt` are accepted spellings of
// the truth (lies matching these are rejected); `d` are house decoys (all false).
const F = (q, a, alt, d, s) => ({ q, a, alt: alt || [], d, s: s ? 1 : 0 });

export const FIB_FACTS = [
  F('In 1932, the Australian military officially went to war against ____.', 'emus', ['emu', 'the emus'], ['kangaroos', 'rabbits', 'koalas']),
  F('A group of flamingos is called a ____.', 'flamboyance', [], ['parade', 'blush', 'fiesta']),
  F('Before it was called Google, the search engine was named ____.', 'BackRub', ['back rub'], ['Googol', 'SearchBot', 'Lookie']),
  F('The national animal of Scotland is the ____.', 'unicorn', ['unicorns'], ['Loch Ness monster', 'haggis', 'bagpipe bird']),
  F('Wombats are famous for producing poop shaped like ____.', 'cubes', ['cube', 'squares', 'dice', 'boxes'], ['stars', 'pyramids', 'spirals']),
  F('In Switzerland, it is illegal to own just one ____, because they get lonely.', 'guinea pig', ['guinea pigs'], ['goldfish', 'cat', 'parrot']),
  F('The first item ever sold on eBay was a broken ____.', 'laser pointer', ['laser pen'], ['toaster', 'lava lamp', 'calculator']),
  F('Bubble wrap was originally invented to be sold as ____.', 'wallpaper', ['textured wallpaper'], ['insulation', 'a shower curtain', 'packing for eggs']),
  F('The dot over a lowercase i or j is called a ____.', 'tittle', [], ['jot', 'speck', 'dimple']),
  F('An octopus has ____ hearts.', 'three', ['3'], ['two', 'five', 'eight']),
  F("A shrimp's heart is located in its ____.", 'head', [], ['tail', 'legs', 'belly']),
  F('The plastic tip on the end of a shoelace is called an ____.', 'aglet', [], ['eyelet', 'endcap', 'lacelet']),
  F('When Fredric Baur, the designer of the Pringles can, died in 2008, some of his ashes were buried in ____.', 'a Pringles can', ['pringles can', 'pringles tube', 'a can of pringles', 'pringles'], ['a chip bag', 'a cereal box', 'a soup can']),
  F("The world's first webcam was set up at Cambridge University to keep an eye on a ____.", 'coffee pot', ['coffee machine', 'coffeepot', 'coffee maker'], ['fish tank', 'parking space', 'bird feeder']),
  F('Nintendo was founded in 1889 as a company that made ____.', 'playing cards', ['cards', 'card games', 'hanafuda cards'], ['umbrellas', 'kites', 'rice cookers']),
  F('Abraham Lincoln is an honoree in the National ____ Hall of Fame.', 'Wrestling', [], ['Bowling', 'Fishing', 'Chess']),
  F('The shortest war in history, between Britain and Zanzibar in 1896, lasted about ____ minutes.', '38', ['38 minutes', 'thirty eight', '40', '45', '39', '37'], ['12', '90', '3']),
  F('Venus spins so slowly that a day on Venus is longer than its ____.', 'year', ['entire year'], ['winter', 'decade', 'summer']),
  F('Botanically speaking, bananas are classified as ____.', 'berries', ['berry', 'a berry'], ['herbs', 'nuts', 'vegetables']),
  F('Mr. Potato Head was the first toy ever advertised on ____.', 'television', ['tv', 'a television', 'television ads'], ['the radio', 'a billboard', 'a blimp']),
  F('When Frisbee inventor Fred Morrison died, his ashes were turned into ____.', 'frisbees', ['frisbee', 'a frisbee', 'flying discs'], ['a firework', 'a garden gnome', 'a bowling ball']),
  F("The word 'salary' comes from the Latin word for ____.", 'salt', [], ['coin', 'bread', 'sweat']),
  F("Sea otters often hold ____ while they sleep so they don't drift apart.", 'hands', ['paws', 'each other', "each other's hands", 'hands with each other'], ['shells', 'driftwood', 'their whiskers']),
  F('The first product ever scanned with a barcode at a store checkout was a pack of ____.', 'gum', ['chewing gum', "wrigley's gum", 'juicy fruit', 'juicy fruit gum'], ['batteries', 'mints', 'shoelaces']),
  F('In the 1830s, ketchup was sold in America as ____.', 'medicine', ['a medicine', 'pills', 'medicine pills', 'a cure'], ['hair dye', 'perfume', 'furniture polish']),
  F('Play-Doh was originally invented to be ____.', 'wallpaper cleaner', ['a wallpaper cleaner', 'cleaner for wallpaper', 'cleaning putty'], ['chewing gum', 'pizza dough', 'modeling clay for dentists']),
  F('The voice actors for Mickey Mouse and Minnie Mouse were also ____ in real life.', 'married', ['husband and wife', 'a married couple', 'married to each other'], ['twins', 'neighbors', 'siblings']),
  F('A bolt of lightning is about ____ times hotter than the surface of the sun.', 'five', ['5', 'five times', '5 times'], ['two', 'fifty', 'a thousand']),
  F('The microwave oven was invented after a researcher noticed that a ____ had melted in his pocket.', 'candy bar', ['chocolate bar', 'chocolate', 'peanut bar', 'candy'], ['crayon', 'lollipop', 'stick of butter']),
  F('Thanks to its islands crossing the 180th meridian, Alaska is the westernmost, northernmost, and ____ state in the U.S.', 'easternmost', ['most eastern', 'eastern most'], ['oldest', 'flattest', 'southernmost']),
  F("Super Mario's original name was ____.", 'Jumpman', ['jump man'], ['Captain Mustache', 'Plumber Pete', 'Hopman']),
  F("Pac-Man's original name in Japan was ____.", 'Puck Man', ['puckman', 'puck-man'], ['Chomp Man', 'Gobble Man', 'Wakka Man']),
  F("The Statue of Liberty's official name is ____.", 'Liberty Enlightening the World', ['liberty enlightening world'], ['The Torch of Freedom', 'Columbia Rising', 'The Harbor Lady']),
  F("The world's oldest recorded joke, from ancient Sumer around 1900 BC, is about ____.", 'farting', ['a fart', 'farts', 'flatulence', 'passing gas', 'fart'], ['taxes', 'a donkey', "a king's beard"]),
  F('For about 20 years, the honorary mayor of Talkeetna, Alaska, was a ____.', 'cat', ['cat named stubbs', 'stubbs the cat', 'a cat'], ['moose', 'golden retriever', 'bear']),
  F('Before alarm clocks were common, people in Britain paid ____ to tap on their windows with long sticks.', 'knocker-uppers', ['knocker uppers', 'knockers up', 'knocker upper', 'knockers-up'], ['window wakers', 'dawn tappers', 'rise callers']),
  F('The oldest animal ever found was a clam, about 507 years old, nicknamed ____.', 'Ming', ['ming the clam'], ['Grandpa', 'Old Tom', 'Shelly']),
  F('Some turtles can breathe through their ____.', 'butts', ['butt', 'rear end', 'cloaca', 'behinds', 'bottoms', 'rear'], ['shells', 'eyelids', 'feet']),
  F('Koalas have ____ that are almost identical to human ones.', 'fingerprints', ['finger prints'], ['teeth', 'earlobes', 'belly buttons']),
  F('There is a species of jellyfish that is biologically ____.', 'immortal', ['unable to die', 'never dies', 'ageless'], ['invisible', 'electric', 'flammable']),
  F('The famous Hollywood sign originally read ____.', 'Hollywoodland', ['hollywood land'], ['Hollywood Hills', 'Hollywoodville', 'Holly Wood Lumber']),
  F('Napoleon was once attacked by a horde of ____.', 'rabbits', ['bunnies', 'rabbit'], ['geese', 'squirrels', 'pigeons']),
  F('During World War II, the future Queen Elizabeth II trained as a ____.', 'mechanic', ['truck mechanic', 'army mechanic', 'driver and mechanic', 'driver'], ['pilot', 'codebreaker', 'cook']),
  F('As a teenager, actor Christopher Walken worked at a circus as a ____ tamer.', 'lion', ['lion tamer'], ['bear', 'snake', 'zebra']),
  F('Martin Luther King Jr., Anne Frank, and Barbara Walters were all born in the same ____.', 'year', ['1929'], ['hospital', 'month', 'city']),
  F('Australia exports ____ to Saudi Arabia.', 'camels', ['camel'], ['sand', 'kangaroos', 'boomerangs']),
  F('Finland hosts an annual world championship for ____ carrying.', 'wife', ['wives', 'wife-carrying'], ['beer', 'grandma', 'sauna stone']),
  F('Hot water can sometimes freeze faster than cold water. This is called the ____ effect.', 'Mpemba', ['mpemba effect'], ['Popsicle', 'Freezeburn', 'Frostline']),
  F('Olympic gold medals are made mostly of ____.', 'silver', [], ['bronze', 'copper', 'brass']),
  F("Thomas Edison's last breath is said to be preserved in a ____ at the Henry Ford Museum.", 'test tube', ['tube', 'glass tube', 'vial'], ['light bulb', 'balloon', 'snow globe']),
  F("Instead of 'hello', Alexander Graham Bell suggested answering the phone by saying ____.", 'ahoy', ['ahoy-hoy', 'ahoy hoy'], ['howdy', 'speak', 'greetings']),
  F('The small Japanese island of Okunoshima is overrun by thousands of friendly wild ____.', 'rabbits', ['bunnies', 'rabbit'], ['deer', 'monkeys', 'cats']),
  F('The longest recorded flight of a chicken lasted ____ seconds.', '13', ['thirteen', '13 seconds'], ['4', '45', '90']),
  F('A 2015 study found that the Scots language has more than 400 words for ____.', 'snow', [], ['rain', 'whisky', 'sheep']),
  F("Twitter's original bird logo had an official name: ____.", 'Larry', ['larry the bird'], ['Tweety', 'Jack', 'Chirpy']),
  F('Rats ____ when they are tickled.', 'laugh', ['giggle', 'chirp', 'squeak'], ['sneeze', 'faint', 'freeze']),
  F('Cleopatra lived closer in time to the moon landing than to the building of ____.', 'the Great Pyramid', ['the great pyramid of giza', 'the pyramids', 'great pyramids', 'pyramid of giza'], ['the Colosseum', 'the Parthenon', 'the Great Wall of China']),
  F('The Hawaiian alphabet has only ____ letters.', '13', ['thirteen', '12', 'twelve'], ['7', '19', '22']),
  F('The University of Oxford is older than the ____ Empire.', 'Aztec', [], ['Roman', 'Persian', 'Egyptian']),
  F('Honey found in ancient Egyptian tombs was still ____.', 'edible', ['good to eat', 'eatable', 'safe to eat'], ['radioactive', 'glowing', 'fizzy']),
  F("Peanuts aren't actually nuts. They are ____.", 'legumes', ['legume', 'beans', 'a legume', 'peas', 'a bean'], ['berries', 'grains', 'fungi']),
  F('A newborn kangaroo is about the size of a ____.', 'jelly bean', ['jellybean', 'bean', 'lima bean', 'grape', 'peanut'], ['golf ball', 'mouse', 'tennis ball']),
  F("A blue whale's heart is roughly the size of a ____.", 'small car', ['car', 'bumper car', 'golf cart'], ['school bus', 'beach ball', 'house']),
  F('In 1957, a BBC April Fools’ report convinced viewers that ____ grows on trees.', 'spaghetti', ['pasta', 'noodles'], ['cheese', 'chocolate', 'bacon']),
  F("The world's largest living organism by area is a ____ in Oregon.", 'fungus', ['mushroom', 'honey fungus', 'giant fungus', 'fungi'], ['redwood tree', 'blackberry bush', 'moss carpet']),
  F('In 1923, jockey Frank Hayes won a horse race despite being ____.', 'dead', ['already dead', 'deceased'], ['blindfolded', 'asleep', 'backwards']),
  F('The town of Boring, Oregon, is officially paired with the town of ____ in Scotland.', 'Dull', [], ['Snooze', 'Drab', 'Yawn']),
  F("A lobster's blood is ____.", 'blue', ['bluish', 'clear blue'], ['purple', 'green', 'orange']),
  F("An ostrich's eye is bigger than its ____.", 'brain', [], ['heart', 'stomach', 'beak']),
  F('Bananas are slightly ____.', 'radioactive', [], ['magnetic', 'electric', 'carbonated']),
  F("Polar bears have ____ skin under their white fur.", 'black', ['dark', 'black skin'], ['pink', 'white', 'blue']),
  F('Giraffes have the same number of neck bones as ____.', 'humans', ['people', 'mice', 'most mammals', 'humans do'], ['snakes', 'birds', 'fish']),
  F('The first driver convicted of speeding in Britain, in 1896, was going ____ mph.', '8', ['eight', '8 mph'], ['25', '40', '15']),
  F("A 'butt' was once an official unit of measurement for ____.", 'wine', ['beer', 'wine and beer', 'ale', 'liquid'], ['cheese', 'flour', 'firewood']),
  F("Iceland has no ____.", 'mosquitoes', ['mosquitos', 'mosquito'], ['sheep', 'traffic lights', 'horses']),
  F('Sloths can hold their breath longer than ____.', 'dolphins', ['dolphin', 'dolphins can'], ['sperm whales', 'sea turtles', 'elephant seals']),
  F('Honeybees can learn to recognize human ____.', 'faces', ['face'], ['voices', 'names', 'handwriting']),
  F('Crows can hold ____ against specific humans for years.', 'grudges', ['a grudge', 'grudge'], ['elections', 'auctions', 'concerts']),
  F('Early carrots were not orange. They were mostly ____.', 'purple', ['purple and yellow', 'yellow', 'white', 'purple or yellow'], ['blue', 'green', 'pink']),
  F('Ancient Romans sometimes used ____ as mouthwash.', 'urine', ['pee', 'wee', 'human urine'], ['snail slime', 'goat milk', 'honey']),
  F('Sweden has a museum dedicated entirely to products that flopped, called the Museum of ____.', 'Failure', [], ['Regret', 'Oops', 'Bad Ideas']),
  F('A single strand of spaghetti is called a ____.', 'spaghetto', [], ['spaghettina', 'noodlet', 'pastino']),
  F('Mosquitoes are more attracted to people who have just been drinking ____.', 'beer', ['alcohol'], ['coffee', 'milk', 'orange juice']),
  F('In 1998, Sony accidentally sold camcorders that could ____.', 'see through clothes', ['see through clothing', 'see through some clothes', 'x-ray clothes'], ['record dreams', 'detect ghosts', 'translate dog barks'], 1),
  F('The fear of being without your mobile phone is called ____.', 'nomophobia', ['no mobile phobia', 'nomophobia'], ['cellophobia', 'textaphobia', 'dialophobia']),
];

// Questions about a player in the room. {name} is replaced; that player answers truthfully.
export const FIB_ABOUT = [
  "What's {name}'s most irrational fear?",
  'What did {name} want to be when they grew up?',
  "What's the weirdest food {name} actually likes?",
  'What would {name} buy first with a million dollars?',
  "What was {name}'s first job?",
  "What's {name}'s hidden talent?",
  'Where would {name} go on a dream vacation?',
  "What's {name}'s go-to karaoke song?",
  'What show has {name} watched way too many times?',
  "What's {name}'s biggest pet peeve?",
  'Which celebrity has {name} been told they look like?',
  "What was {name}'s childhood nickname?",
  "What's the most useless thing {name} owns?",
  "What's {name}'s guilty pleasure snack?",
  "What's the strangest thing {name} has ever eaten?",
  "What's {name}'s favorite smell?",
  'What skill does {name} wish they had?',
  'If {name} were an animal, what would they be?',
  "What's {name}'s most-used emoji?",
  'What was the last thing {name} searched for online?',
  "What's {name}'s most controversial food opinion?",
  'What would {name} name a pet goat?',
  "What's the worst gift {name} has ever received?",
  "What's the first thing {name} would do if they won the lottery?",
  { t: "What's the worst date {name} has ever been on?", s: 1 },
  { t: "Who is {name}'s celebrity crush?", s: 1 },
  { t: "What's the dumbest thing {name} has done while drunk?", s: 1 },
  { t: "Where is the weirdest place {name} has fallen asleep?", s: 1 },
];
