// Moojority questions. Plain strings are free-answer; {t, o:[...]} are pick-one.
const C = (t, o, s) => ({ t, o, s: s ? 1 : 0 });
const SP = (t) => ({ t, s: 1 });

export const HERD_QUESTIONS = [
  'Name a pizza topping',
  'Name a breakfast cereal',
  'Name a red fruit',
  'Name a superhero',
  'Name an animal you would see on a farm',
  'Name a color of the rainbow',
  'Name a sport played with a ball',
  'Name a planet',
  'Name a vegetable kids hate',
  'Name something you take to the beach',
  'Name a dog breed',
  'Name a fast food restaurant',
  'Name a famous wizard',
  'Name a board game',
  'Name a holiday',
  'Name something that is yellow',
  'Name a musical instrument',
  'Name a kitchen appliance',
  'Name a Disney movie',
  'Name an ice cream flavor',
  "Name a bird that can't fly",
  'Name a sea creature',
  'Name a candy bar',
  'Name a breakfast food',
  'Name a country in Europe',
  'Name a car brand',
  'Name something you find in a bathroom',
  'Name a school subject',
  'Name a dessert',
  'Name a famous scientist',
  'Name an animal with stripes',
  'Name a type of cheese',
  'Name something you plug in',
  'Name a social media app',
  'Name something people are afraid of',
  'Name a job that comes with a uniform',
  'Name a type of shoe',
  'Name a word that rhymes with cat',
  'Name something with wheels',
  'Name a cartoon character',
  'Name a soda',
  'Name a famous detective',
  'Name a reptile',
  'Name something cold',
  'Name a kind of pasta',
  'Name a Christmas song',
  'Name a sandwich',
  'Name a kind of nut',
  'Name a hot drink',
  'Name a big city in the USA',
  'Name a toy',
  'Name a fairy tale',
  'Name something you find in a forest',
  'Name a citrus fruit',
  'Name a famous band',
  'Name something that flies',
  'Name something purple',
  'Name a bug',
  'Name a famous monster',
  'Name a farm animal that says moo',
  'Name a shape',
  'Name something you do in the morning',
  'Name a type of bread',
  'Name something in a toolbox',
  'Name a winter sport',
  'Name a famous painter',
  'Name a spice',
  'Name a pet name for a goldfish',
  'Name a kind of bear',
  'Name a famous castle',
  'Name a thing you find at a birthday party',
  'Name a video game',
  'Name a vegetable that is green',
  'Name a famous pirate',
  'Name a sauce',
  'Name something you see in the sky',
  SP('Name a cocktail'),
  SP('Name a beer brand'),
  SP('Name a bad habit'),
  SP('Name a reason to break up with someone'),
  SP('Name something you do on a first date'),
  SP('Name a famous celebrity couple'),
  C('Cats or dogs?', ['Cats', 'Dogs']),
  C('Best day of the week?', ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
  C('Best season?', ['Spring', 'Summer', 'Fall', 'Winter']),
  C('Beach or mountains?', ['Beach', 'Mountains']),
  C('Pancakes or waffles?', ['Pancakes', 'Waffles']),
  C('Pick a number from 1 to 5', ['1', '2', '3', '4', '5']),
  C('Best pizza topping?', ['Pepperoni', 'Mushroom', 'Pineapple', 'Sausage', 'Just cheese']),
  C('Which superpower?', ['Flying', 'Invisibility', 'Teleporting', 'Mind reading']),
  C('Coffee or tea?', ['Coffee', 'Tea']),
  C('Early bird or night owl?', ['Early bird', 'Night owl']),
  C('Best meal of the day?', ['Breakfast', 'Lunch', 'Dinner', 'Midnight snack']),
  C('Which is scariest?', ['Clowns', 'Spiders', 'Heights', 'Ghosts']),
  C('Pick a color', ['Red', 'Blue', 'Green', 'Yellow']),
  C('Books or movies?', ['Books', 'Movies']),
  C('Sweet or salty?', ['Sweet', 'Salty']),
  C('Text or call?', ['Text', 'Call']),
  C('Ketchup or mustard?', ['Ketchup', 'Mustard']),
  C('Who wins a fight?', ['A gorilla', 'A grizzly bear', 'A lion', '100 angry ducks']),
  C('Toilet paper roll: over or under?', ['Over', 'Under']),
  C('Is a hot dog a sandwich?', ['Yes', 'No']),
  C('Rock, paper, or scissors?', ['Rock', 'Paper', 'Scissors']),
  C('Pick a card suit', ['Hearts', 'Diamonds', 'Clubs', 'Spades']),
  C('Shower in the morning or at night?', ['Morning', 'Night']),
  C('Pineapple on pizza?', ['Yes please', 'Absolutely not']),
  C('Heads or tails?', ['Heads', 'Tails']),
  C('Best way to eat potatoes?', ['Fries', 'Mashed', 'Baked', 'Chips']),
  C('Fight one horse-sized duck or 100 duck-sized horses?', ['One horse-sized duck', '100 duck-sized horses']),
  C('Best ice cream flavor?', ['Vanilla', 'Chocolate', 'Strawberry', 'Mint chip']),
  C('Which pet would you pick?', ['Dog', 'Cat', 'Fish', 'Lizard', 'Bird']),
  C('Sunrise or sunset?', ['Sunrise', 'Sunset']),
  C('Pick a letter', ['A', 'B', 'C', 'D']),
  C('Best sandwich bread?', ['White', 'Wheat', 'Sourdough', 'Rye']),
  C('Which would you rather explore?', ['Space', 'The deep ocean']),
  C('Best way to travel?', ['Car', 'Train', 'Plane', 'Boat']),
  C('Pick a famous duo', ['Salt and pepper', 'Peanut butter and jelly', 'Mac and cheese', 'Milk and cookies']),
  C('Which is the best fruit?', ['Apple', 'Banana', 'Strawberry', 'Mango']),
  C('Is cereal a soup?', ['Yes', 'No']),
  C('Best drink at a party?', ['Beer', 'Wine', 'Cocktails', 'Shots'], 1),
  C('Worst place for a first date?', ['The movies', 'Bowling', 'A fancy dinner', "Your parents' house"], 1),
  C('Best hangover cure?', ['Greasy food', 'Water', 'Sleep', 'More drinks'], 1),
];
