// Telephoney starter sentences (used as "need an idea?" suggestions and as fill-ins).
export const PHONE_STARTERS = [
  'A wizard who is afraid of his own hat',
  'Two snails racing for the last slice of pizza',
  'A grandma winning a skateboard contest',
  'The moon falling in love with a lighthouse',
  'A dog teaching a cat how to swim',
  'A dinosaur stuck in a revolving door',
  'An astronaut eating spaghetti in zero gravity',
  'A ghost who is terrible at hide and seek',
  'A shark opening a lemonade stand',
  'A cowboy riding a giant hamster into the sunset',
  'A robot getting a haircut',
  'A family of ducks going through airport security',
  'A volcano erupting with popcorn',
  'A penguin who lost its tuxedo',
  'A knight fighting a very small dragon',
  'A cactus at a balloon party',
  'Three bears sharing one umbrella',
  'A chicken laying a golden basketball',
  'A pirate who is seasick',
  'A tiny elephant in a teacup',
  'A sandwich that is too tall to eat',
  'A frog on a first date with a fly',
  'A mermaid stuck in a fishbowl',
  'An octopus playing four instruments at once',
  'A superhero who only saves pigeons',
  'A snowman sweating at the beach',
  'A detective who is a goldfish',
  'A banana slipping on a person',
  'A vampire scared of a garlic pizza',
  'A sloth winning a race',
  'A giraffe trying to hide behind a tree',
  'A haunted bouncy castle',
  'A worm wearing a top hat',
  'An alien ordering fast food',
  'A cat ruling a kingdom of dogs',
  'A ninja tiptoeing through a pile of bubble wrap',
  'A lighthouse with a sleepy keeper',
  'A burger with legs running away from a chef',
  'A bee working in an office',
  'A unicorn stuck in a traffic jam',
  'A king who is very tiny',
  'A tornado picking up a cow',
  'A spaceship made of cheese',
  'A dog driving a bus full of cats',
  'A bear stealing a picnic basket',
  'A ballerina hippo on stage',
  'A mummy unravelling on a roller coaster',
  'A fish riding a bicycle up a hill',
  'A bird building a nest out of spaghetti',
  'A treasure chest full of socks',
  'A clown sneezing confetti',
  'A turtle with a rocket on its back',
  'A wizard turning a frog into a prince by accident',
  'Two raccoons robbing a bank',
  'A lobster lifeguard',
  'A lamp that is afraid of the dark',
  'A sheep knitting a sweater out of itself',
  'A baby giving a business presentation',
  'A whale in a swimming pool',
  'A dragon roasting marshmallows',
];
