// Hot Seat prompts: "Who's most likely to ...". S() = spicy-only.
const S = (t) => ({ t, s: 1 });

export const SEAT_PROMPTS = [
  'survive a zombie apocalypse',
  'become famous',
  'forget their own birthday',
  'get lost in their own neighborhood',
  'win a hot dog eating contest',
  'cry at a commercial',
  'accidentally join a cult',
  'adopt ten cats',
  'become a millionaire',
  'be late to their own wedding',
  'talk their way out of a speeding ticket',
  'eat food off the floor',
  'go viral for something embarrassing',
  'survive on a deserted island',
  'laugh at exactly the wrong moment',
  'become president',
  'get kicked out of a museum',
  'sleep through an earthquake',
  'fall for an obvious prank',
  'know every word to every song',
  'reply-all by accident',
  'win a staring contest',
  'secretly be a spy',
  'trip over absolutely nothing',
  'argue with a stranger online',
  'become a reality TV star',
  'bring snacks to every hangout',
  'give the best advice',
  'burn water',
  'talk to their plants',
  'befriend a wild animal',
  'show up in pajamas',
  'win the lottery and lose the ticket',
  'become a famous chef',
  'name their car',
  'binge a whole series in one day',
  'get abducted by aliens',
  'laugh at their own jokes',
  'write a best-selling novel',
  'have 100 browser tabs open right now',
  'start a band',
  'own a pet snake',
  'get stuck in a revolving door',
  'run a marathon on a dare',
  'become a cult leader',
  'move to another country on a whim',
  'still have their baby teeth in a box',
  'scream at a horror movie',
  'eat the last slice without asking',
  'cheat at board games',
  'cry at a wedding',
  'get a pet goat',
  'live to 100',
  'become an influencer',
  'lose their phone while holding it',
  'start a food fight',
  'survive a horror movie',
  'be the first to die in a horror movie',
  'get banned from a casino',
  'become a superhero',
  'become a supervillain',
  'adopt a raccoon',
  'go to space',
  'fall asleep at a party',
  'take 200 selfies on vacation',
  'forget why they walked into a room',
  'have a secret twin',
  'win a dance battle',
  'climb Mount Everest',
  'invent something useless',
  'get famous on a cooking show',
  'never return a borrowed book',
  'win an argument with a toddler',
  'lose an argument with a toddler',
  'become a professional napper',
  'get a terrible tattoo',
  S('text their ex at 3 a.m.'),
  S('end up in jail for one night'),
  S('get married in Vegas'),
  S('show up hungover to work'),
  S('hook up at a wedding'),
  S('get kicked out of a bar'),
  S('fake a sick day'),
  S('go skinny dipping'),
  S('date two people at once'),
  S('start a fight at karaoke'),
  S('drunk-order something ridiculous online'),
  S('have the wildest search history'),
];
