// Sketchy drawing prompts. Strings are family-friendly; S() = spicy-only.
const S = (t) => ({ t, s: 1 });

export const SKETCH_PROMPTS = [
  'A nervous hot dog',
  "Grandma's secret fight club",
  'A cat filing its taxes',
  "The world's saddest birthday party",
  'A shark at the dentist',
  'A snowman on vacation',
  'A very confident potato',
  'An octopus doing laundry',
  'A vampire at the beach',
  'A haunted toaster',
  'A cow on a skateboard',
  'The last slice of pizza',
  'A robot learning to love',
  "A dog's job interview",
  'A ghost trying on clothes',
  'A banana in witness protection',
  "Bigfoot's selfie",
  'A wizard stuck in traffic',
  'A dinosaur at prom',
  'A very sad cloud',
  "The tooth fairy's day job",
  'A spider wearing shoes',
  'A mermaid with a desk job',
  'A broccoli bodybuilder',
  'A penguin lost in the desert',
  'A lazy superhero',
  'An angry pineapple',
  'A llama at a wedding',
  'A romantic dinner for two snails',
  "A frog king's coronation",
  'A haunted shopping cart',
  'A horse riding a horse',
  'The moon with a toothache',
  'A volcano with the hiccups',
  'The sock puppet uprising',
  "An alien's first taco",
  'A tiny chef cooking a giant egg',
  "The world's strongest baby",
  "A pirate's grocery list",
  'A bear doing yoga',
  'Pizza delivery on Mars',
  'A cactus that wants a hug',
  'An elephant hiding behind a lamp post',
  'A unicorn with a mullet',
  'A tree stuck in a cat',
  'A fish riding a bicycle',
  "Grandpa's motorcycle gang",
  'A burrito sleeping bag',
  'The Eiffel Tower on a diet',
  'A robot dog walking a human',
  'A sandwich with stage fright',
  'A bee with a tiny briefcase',
  "Dracula's morning routine",
  "Toilet paper's revenge",
  'A giraffe in a turtleneck',
  'A snail racing a turtle',
  'An ant carrying a donut',
  'A lemon getting a tan',
  "The world's worst magician",
  'A ninja tripping over a cat',
  'A haunted rubber duck',
  'A sloth at a rock concert',
  'A walrus at a spa',
  'A hamster lifting weights',
  'A sumo wrestler on a tightrope',
  'A clown car breaking down',
  'A kangaroo with an empty pouch',
  'Two pigeons on a date',
  'A dog wearing pants',
  'A very tired lighthouse',
  'A shy volcano',
  'An avocado at the gym',
  'A robot crying',
  'A smug bowl of soup',
  'A cowboy riding a chicken',
  'A snowman at a barbecue',
  'A dragon afraid of the dark',
  'A lumberjack hugging a tree',
  'Sushi doing ballet',
  "An astronaut's lost sock",
  'A dog who thinks it is a cat',
  'A crocodile tooth fairy',
  'An evil teddy bear',
  'A cheeseburger in love',
  'Sheep counting people',
  'A lonely sock on a beach',
  "An owl's book club",
  'A pickle in a tuxedo',
  'A mermaid with legs',
  'A very small giraffe',
  'A dog walking a dog',
  "A baby's first bank heist",
  'A cloud raining spaghetti',
  'The king of the squirrels',
  'A monster scared of the kid under the bed',
  "A snowman's summer job",
  'Popcorn having a panic attack',
  'A grumpy rainbow',
  'A disco ball in a library',
  'A lobster in a hot tub',
  'A bowling ball with feelings',
  'A mouse lifting a cat',
  'A pizza wearing a pizza',
  'A rock band made of rocks',
  'A cheese wheel rolling downhill',
  'An octopus on a unicycle',
  'Cereal swimming in a milk pool',
  'A fork in the road',
  "It's raining cats and dogs",
  'Butterflies in my stomach',
  'The elephant in the room',
  'A couch potato',
  'A night owl',
  'Spilling the beans',
  'A piece of cake',
  'Cold feet',
  'When pigs fly',
  'A bookworm',
  'Brain freeze',
  'Monkey business',
  'A cat burglar',
  'A fish out of water',
  "A dog's dream vacation",
  'A pencil with writer’s block',
  "A potato's family portrait",
  'A tornado made of kittens',
  'An alien abducting a cow',
  'A barber for porcupines',
  'A robot at a yard sale',
  'A pumpkin with a spray tan',
  'A haunted vending machine',
  'A beaver building a skyscraper',
  'A goldfish planning an escape',
  'A turtle with a jetpack',
  'A pigeon stealing a whole sandwich',
  'A banana slipping on a person',
  'A tired bat at noon',
  'A chicken crossing the road on a scooter',
  'A grandma skydiving',
  'A worm wearing glasses',
  'A melting ice cream cone crying',
  'A carrot in a horror movie',
  'A pirate ship in a bathtub',
  'A dentist who is a dinosaur',
  'A pug in a spacesuit',
  'A tooth with a mustache',
  'A cat-shaped cloud scaring a dog',
  'A mummy unravelling at a party',
  'A queen eating spaghetti',
  'A raccoon running a bakery',
  'An exhausted alarm clock',
  'A muscular baby carrot',
  'A jellyfish with a perm',
  S('A bachelorette party for ghosts'),
  S('The walk of shame'),
  S('A terrible hangover'),
  S('A drunk text'),
  S('Speed dating for vegetables'),
  S('A very awkward first kiss'),
  S('Netflix and chill'),
  S('A wine mom'),
  S('A bachelor party in Vegas'),
  S('Beer goggles'),
  S('A dating app disaster'),
  S('A midlife crisis'),
  S('Skinny dipping'),
  S('A breakup text'),
  S('A gym selfie'),
  S('Tequila regrets'),
  S('The friend zone'),
  S('Love handles'),
  S('A hot mess'),
  S('Morning breath'),
  S('Couples therapy for salt and pepper'),
  S('An office romance'),
  S('Getting dumped by a robot'),
  S('A pickle at pole dancing class'),
];
