// Content for the table games: Tick Tock Boom categories, High Noon fake-outs, Forehead words.

export const BOMB_CATEGORIES = [
  'Things in a kitchen',
  'Animals with four legs',
  'Pizza toppings',
  'Words that start with B',
  'Things that are red',
  'Cartoon characters',
  'Countries',
  'Things at the beach',
  'Sports',
  'Fruits',
  'Car brands',
  'Things that fly',
  'Jobs',
  'Things in a classroom',
  'Breakfast foods',
  'Superheroes',
  'Board games',
  'Things that are cold',
  'Musical instruments',
  "Words that rhyme with 'day'",
  'Things with buttons',
  'Dog breeds',
  'Things you take camping',
  'Desserts',
  'Body parts',
  'Things that are round',
  'Ice cream flavors',
  'Things that smell bad',
  'Things in a bathroom',
  'Vegetables',
  'Things that are sticky',
  "Words that end in 'ing'",
  'Things with wheels',
  'Things in the ocean',
  'Things that are green',
  'Famous cartoon dogs',
  'Things you find in a purse',
  'Things in a toolbox',
  'Things that make noise',
  'Things that are soft',
  'Things in a park',
  'Things that are hot',
  'Halloween costumes',
  'Things that are yellow',
  'Kinds of bread',
  "Words that start with 'ST'",
  'Things with a screen',
  'Things you can throw',
  'Things in a refrigerator',
  'Insects and bugs',
  'Things that are fast',
  'Things you wear on your head',
  'Flavors of chips',
  'Things in a hospital',
  'Holidays',
  'Things you plug in',
  'Things that are sweet',
  'Things in space',
  'Farm animals',
  'Video games',
  'Things that are small',
  'Movies with animals in them',
  'Things in a grocery store',
  'Weather words',
  "Things with 'fire' in the name",
  'Things you can open',
  'Things that are blue',
  'Kitchen utensils',
  'Things that bounce',
  'Disney movies',
  'Things that are expensive',
  'Words that rhyme with cat',
  'Things in a backyard',
  'Things that have stripes',
  'School subjects',
  'Things that come in pairs',
  'Things with a lid',
  'Birds',
  "Words that start with 'PL'",
  'Breakfast cereals',
  'Things in a car',
  'Things you do in the morning',
  'Famous wizards and witches',
  'Things that melt',
  'Sandwiches',
  'Things at a birthday party',
  'Pasta shapes',
  'Things at a zoo',
  'Things with a tail',
  'Things that glow',
  'Things that are sharp',
  'Things you say on the phone',
  'Cities',
  'Things that are wet',
  'Things you find in a desk drawer',
  "Words with double 'O'",
  'Snacks at the movies',
  'Things that are loud',
  'Things a pirate would say',
  'Things in a fairy tale',
  { t: 'Cocktails', s: 1 },
  { t: 'Things you do at a bar', s: 1 },
  { t: 'Bad first date moves', s: 1 },
  'Things at a wedding',
];

export const NOON_FAKES = ['DRAWER', 'DRAMA', 'DRAGON', 'DRAIN', 'DREAM', 'DRAFT', 'DRAPE', 'DROWN', 'DRAWN?', 'BRAW', 'DRIP', 'STRAW', 'DROOL', 'DRUM', 'DRAG'];

const W = (s) => s.split(',').map((x) => x.trim());

export const HEAD_DECKS = {
  Animals: W('Elephant, Penguin, Giraffe, Kangaroo, Octopus, Flamingo, Sloth, Shark, Owl, Squirrel, Camel, Crocodile, Peacock, Bat, Jellyfish, Hedgehog, Gorilla, Llama, Zebra, Dolphin, Raccoon, Skunk, Porcupine, Koala, Beaver, Moose, Panda, Lobster, Chameleon, Woodpecker, Seal, Hippo, Rhino, Turkey, Goldfish, Spider, Snail, Butterfly, Polar bear, Chicken'),
  Food: W('Spaghetti, Pancakes, Sushi, Popcorn, Taco, Watermelon, Hot dog, Pizza, Cupcake, Pretzel, Lasagna, Broccoli, Burrito, Waffle, Cotton candy, Corn on the cob, Pineapple, Meatball, Lollipop, Nachos, Avocado, Peanut butter, Cheeseburger, Bacon, Grilled cheese, Donut, French fries, Pickle, Marshmallow, Smoothie, Omelette, Chicken nuggets, Fortune cookie, Banana split, Ramen'),
  'Act it out': W('Brushing teeth, Riding a horse, Surfing, Juggling, Skydiving, Walking a dog, Changing a diaper, Fishing, Doing yoga, Playing guitar, Climbing a mountain, Baking a cake, Swimming, Taking a selfie, Ice skating, Bowling, Mowing the lawn, Sneezing, Driving a bus, Milking a cow, Painting a wall, Riding a roller coaster, Shoveling snow, Boxing, Jumping rope, Rowing a boat, Typing, Sleepwalking, Washing a car, Conducting an orchestra'),
  Jobs: W('Firefighter, Astronaut, Dentist, Chef, Pilot, Lifeguard, Magician, Plumber, Teacher, Mail carrier, Farmer, Detective, Clown, Lumberjack, Barber, Zookeeper, Librarian, Referee, Waiter, Scientist, Cowboy, Photographer, Nurse, Judge, DJ, Bus driver, Ballerina, Mechanic, Pirate, Surgeon'),
  Places: W('Beach, Library, Airport, Hospital, Zoo, Movie theater, Volcano, Castle, Desert, Jungle, Igloo, Space station, Bowling alley, Supermarket, Haunted house, Water park, Farm, Gas station, Museum, Lighthouse, Circus, Laundromat, Mountain, Ski resort, Cave, Submarine, Treehouse, Las Vegas, Paris, The North Pole'),
  'Around the house': W('Toaster, Couch, Refrigerator, Toothbrush, Vacuum cleaner, Lamp, Blanket, Microwave, Remote control, Doorbell, Bathtub, Pillow, Washing machine, Alarm clock, Mirror, Stairs, Fireplace, Mailbox, Dishwasher, Bookshelf, Ceiling fan, Smoke detector, Toilet, Oven mitt, Garden hose, Welcome mat, Curtains, Laundry basket, Key, Light switch'),
  Characters: W('Santa Claus, Spider-Man, Harry Potter, Shrek, Batman, Mickey Mouse, SpongeBob, Pikachu, Darth Vader, Elsa, Mario, Sherlock Holmes, Cinderella, Dracula, Frankenstein, The Hulk, Winnie the Pooh, Peter Pan, Superman, Yoda, Homer Simpson, Scooby-Doo, Tarzan, Robin Hood, The Grinch, Cookie Monster, Wonder Woman, Pinocchio, Captain Hook, Big Bird'),
  'Sports & games': W('Soccer, Golf, Bowling, Surfing, Chess, Boxing, Tennis, Karate, Basketball, Ice hockey, Skateboarding, Gymnastics, Archery, Fencing, Wrestling, Ping pong, Baseball, Hide and seek, Tug of war, Darts, Snowboarding, Rock climbing, Badminton, Hopscotch, Limbo, Volleyball, Sumo wrestling, Marathon, Rodeo, Water polo'),
  'World famous': W('Eiffel Tower, Mona Lisa, Statue of Liberty, Great Wall of China, The Pyramids, Big Ben, Mount Everest, Titanic, Stonehenge, Niagara Falls, Hollywood sign, Leaning Tower of Pisa, Colosseum, Grand Canyon, Taj Mahal, Mount Rushmore, Golden Gate Bridge, Loch Ness Monster, Moon landing, Times Square'),
};

export const HEAD_SPICY = {
  'After dark': W('Hangover, Blind date, Bachelor party, Walk of shame, Speed dating, Karaoke night, Tequila, Wedding crasher, Love letter, Pickup line, Skinny dipping, Hot tub, Dating app, Breakup, Bar fight, Last call, Beer pong, Spin the bottle, Truth or dare, Bad tattoo'),
};
