// Zinger Ring prompts. Strings are family-friendly; {t, s:1} objects are spicy-only.
const S = (t) => ({ t, s: 1 });

export const ZINGER_PROMPTS = [
  'The worst thing to hear from your dentist while your mouth is full of tools',
  'A rejected flavor of potato chips',
  'What your pet is secretly writing in its diary',
  'The worst name for a cruise ship',
  'A terrible thing to say during a job interview',
  'The real reason the dinosaurs went extinct',
  'What aliens would complain about after visiting Earth',
  'A bad slogan for a funeral home',
  'The worst superpower to get stuck with',
  'Something you should never say to a mime',
  'A better name for Monday',
  'What the Statue of Liberty is thinking right now',
  "The world's least popular theme park ride",
  'A fortune cookie message that would ruin your whole day',
  'A rejected Olympic sport',
  'The worst thing to find in your burrito',
  'What the moon does when nobody is looking',
  'A terrible name for a hair salon',
  'A new law that only applies on Tuesdays',
  'What your fridge would say if it could talk',
  'A rejected name for a new planet',
  'The most useless app idea ever',
  'The worst thing to engrave on a trophy',
  'Something you should not bring to a sleepover',
  'A sign that your GPS secretly hates you',
  'The real reason the chicken crossed the road',
  'The worst animal to hire as your lawyer',
  'A rejected crayon color',
  'The worst thing to say on your first day at a new school',
  'What your socks talk about in the dryer',
  'A terrible motto for a bakery',
  'The worst gift to give a teacher',
  'A rejected animated movie about talking furniture',
  'Something a pirate would put on a dating profile',
  'What babies are really thinking',
  'The worst way to start a wedding toast',
  'A rejected ice cream flavor',
  "The world's worst bedtime story title",
  'What the tooth fairy actually does with all the teeth',
  "Something you'd hate to hear the pilot say",
  'A bad name for a racehorse',
  'The worst thing to find under your bed',
  'The most disappointing prize in a cereal box',
  'A terrible slogan for a hospital',
  'The worst thing to shout during a magic show',
  'What your houseplant would text you',
  'A bad idea for a reality TV show',
  'Something that should never be self-driving',
  'The worst part about being a ghost',
  'A rejected superhero sidekick',
  "The real secret ingredient in grandma's cookies",
  'What Bigfoot posts online',
  'A rejected holiday',
  'The worst possible password',
  'Something you should never put in a microwave',
  'The worst job at the North Pole',
  "What a cat thinks 'fetch' means",
  'A rejected title for a Shakespeare play',
  'The worst name for your Wi-Fi network',
  'A strange item to find in a vending machine',
  'The worst thing to say right after someone sneezes',
  'A bad name for a gym',
  'What cows are really mooing about',
  'The least helpful advice for a new driver',
  'A food that would make a terrible superhero',
  'The worst thing to bring to show-and-tell',
  "A sign you're at a really bad restaurant",
  'What the Easter Bunny does the rest of the year',
  'A rejected name for the next smartphone',
  'The worst thing to hear from a skydiving instructor',
  'A new rule that would make chess more exciting',
  'A rejected zoo exhibit',
  'The worst thing to do in a library',
  'What lives at the bottom of your laundry basket',
  'A terrible name for a band made of grandmas',
  'The worst flavor of toothpaste',
  'Something that would make a picnic awkward',
  'The worst mascot for a sports team',
  'A great reason to get kicked out of a museum',
  'What your shadow does at night',
  'The worst way to spend a million dollars',
  'A rejected warning label',
  'A terrible thing for a doctor to say during a checkup',
  'The worst snack for a long car ride',
  'The worst question to ask a fortune teller',
  'A strange thing to collect',
  'A terrible way to propose',
  'What penguins argue about',
  'A rejected boy band name',
  'The worst thing to step on barefoot',
  'A bad name for a cologne',
  'The real reason your phone battery dies so fast',
  'A new Olympic event for lazy people',
  'What dogs dream about',
  'A better use for a paperclip',
  'The weirdest thing a squirrel could steal',
  'The worst new piece to add to a board game',
  'A rejected greeting card message',
  'What the Mona Lisa is smirking about',
  'A bad name for a chain of dentist offices',
  'The worst place to get the hiccups',
  'A terrible thing to put on a pizza',
  'A rejected building block set',
  'What astronauts really do all day in space',
  'The worst message to find in a bottle',
  "A terrible theme for a kid's birthday party",
  'The most dramatic way to quit a job',
  'The worst toy for a toddler',
  'The worst way to wake someone up',
  'What clouds gossip about',
  'A secret talent that is completely useless',
  'The worst thing to bring on a first date',
  'A weird thing to say to a baby',
  'A terrible name for a boat',
  'The worst flavor of gum',
  "Something you shouldn't buy secondhand",
  'The real reason T. rex had tiny arms',
  'A new name for the color beige',
  "The world's most boring superhero",
  'The worst question to ask a ghost',
  'A rejected title for a famous painting',
  "What your car does when you're not around",
  'An unusual thing to bring to a job interview',
  'What happens at a slumber party for grandmas',
  'The worst thing to find in a hotel room',
  'A terrible movie sequel',
  'A tradition your family should start',
  'The best excuse for being late',
  "The worst thing to say when meeting your partner's parents",
  'A bad slogan for an airline',
  'What a lobster would order at a seafood restaurant',
  'A rejected frozen yogurt topping',
  'A fancy new name for a hot dog',
  "The secret third thing that comes after 'death and taxes'",
  'Something that is definitely not allowed at the beach',
  'The worst thing to scream on a roller coaster',
  "A word that should exist but doesn't",
  'What your eyebrows would say if they could talk',
  'The worst way to end a phone call',
  'A terrible thing to hear while getting a haircut',
  'The worst name for a dog',
  'What a snowman fears most',
  'The real reason pirates wore eye patches',
  'A rejected emoji',
  'A movie title that would make you leave the theater',
  'The worst job for a sloth',
  'Something you would never say at a barbecue',
  'A bad nickname for your boss',
  'What really happened to the other sock',
  "A sentence you'd hate to hear from your mechanic",
  'A product that should never come in extra large',
  'The worst thing you could say to a lifeguard',
  'A rejected wizard spell',
  'The worst thing to hear over the airport speaker',
  'A strange hobby for a robot',
  'The worst place to hide a birthday present',
  'The real reason cats knock things off tables',
  'A rejected fairy tale princess',
  'A sound you never want to hear on an airplane',
  "What the 'check engine' light is really trying to tell you",
  'The worst theme for a wedding',
  'A weird thing to say while hugging someone',
  'The least intimidating name for a wrestler',
  'A hot sauce name that is also a warning',
  'A rejected sandwich name',
  'What the Loch Ness Monster does for fun',
  'A terrible thing to find in your salad',
  'A rule that should exist at every party',
  'The worst text to get from your mom',
  "What really goes on in the teachers' lounge",
  'A baby name that is a huge red flag',
  'A rejected title for a self-help book',
  'The worst superhero catchphrase',
  'What frogs think about all day',
  'Something that would make Monday even worse',
  'The first thing a robot would do on vacation',
  'A terrible nickname for a grandma',
  'A bad name for a coffee shop',
  'The worst thing to forget on a camping trip',
  'What the walls of your house would say about you',
  'A sport that would be improved by adding bees',
  'A strange request for a genie',
  'The worst flavor of birthday cake',
  'What should replace handshakes',
  'The best name for a pet rock',
  'A cheap substitute for a Christmas tree',
  "Something you'd find in a wizard's junk drawer",
  'The weirdest place to fall asleep',
  'A rejected nursery rhyme',
  'The scariest thing to find in your refrigerator',
  'The motto of a very lazy superhero team',
  'The worst thing to say to a waiter',
  'A rejected flavor of soda',
  'What a goldfish is thinking during its three-second memory',
  'The worst sound for an alarm clock',
  'A terrible name for a bakery',
  'The worst thing to put in a time capsule',
  'An Olympic sport for people with no skills',
  'The worst thing to find in your shoe',
  'What a mosquito would say in its defense',
  'A rejected Thanksgiving side dish',
  'The worst thing to say during a eulogy for a goldfish',
  'A terrible name for a rock band',
  'The least exciting treasure in a treasure chest',
  "A sign that you're the villain of the story",
  'What the ocean is mad about',
  'The worst thing to hear from a tattoo artist',
  'A bad name for a sports car',
  "Something you shouldn't say to a bear",
  'The worst job interview question',
  'An awkward thing to say in an elevator',
  'A rejected name for a hurricane',
  'What a vampire eats when it is on a diet',
  'The worst superhero origin story',
  'A terrible name for a law firm',
  'The worst thing to hear at a car wash',
  "The worst way to celebrate a cat's birthday",
  'The least scary haunted house attraction',
  'What pigeons are plotting',
  'A useless invention that would still sell millions',
  S('The worst thing to hear during a romantic dinner'),
  S('A rejected name for a dating app'),
  S("Something you shouldn't say on a first date"),
  S('The worst pickup line of all time'),
  S('What your browser history says about you'),
  S('The real reason you got kicked out of the bar'),
  S("A bad thing to find in your date's apartment"),
  S('The worst thing to text your ex at 2 a.m.'),
  S('What not to say during a breakup'),
  S('A rejected cocktail name'),
  S('The worst thing to say in a best man speech'),
  S("A hangover cure that definitely doesn't work"),
  S("Something you'd never want to hear through the hotel wall"),
  S("The worst thing to find on your partner's phone"),
  S('A terrible name for a wine'),
  S('What happens in Vegas that should NOT stay in Vegas'),
  S("Your worst roommate's worst habit"),
  S('The worst thing to bring to a bachelorette party'),
  S('A dating profile red flag'),
  S('The most awkward thing to say to your boss at the holiday party'),
  S('A bad reason to get a tattoo'),
  S('The worst tattoo to get on your forehead'),
  S('The worst thing to say in a job interview after three margaritas'),
  S('An embarrassing thing to drunk-order online'),
  S('What your therapist says about you behind your back'),
  S('The worst thing to yell during a yoga class'),
  S('A rejected name for an energy drink'),
  S('The worst safe word'),
  S('Something you should never do on a video call'),
  S('What really happens at the office holiday party'),
  S('The worst anniversary gift'),
  S('A terrible name for a perfume'),
  S('A sign that your date is going terribly'),
  S('The worst name for a nightclub'),
  S('Something you should never say to a bouncer'),
  S('A rejected reality dating show'),
  S('What your landlord is doing with your security deposit'),
  S('The worst wedding hashtag'),
  S('The worst emoji to send your boss'),
  S('A terrible slogan for a casino'),
  S('The real reason your ex texted you'),
  S('The most embarrassing thing to get caught googling'),
  S("The worst thing to whisper in someone's ear"),
  S('A sign your rideshare driver is a little too chatty'),
  S('A bad name for a brewery'),
  S('The worst way to announce a pregnancy'),
  S("What's really in a hot dog"),
  S('The most awkward place to run into your ex'),
  S('A bad excuse for calling in sick'),
  S("Something you'd regret posting"),
  S('The name of your boat when you have a midlife crisis'),
  S('What the walls of a college dorm have seen'),
  S('A rejected sympathy card message'),
  S('The worst thing to say to a nudist'),
  S('The real reason the wedding was canceled'),
  S("A terrible thing to say when you meet your date's kids"),
  S('The most suspicious thing to buy at 3 a.m.'),
  S('What grown-ups do after the kids go to bed'),
  S('The worst slogan for a bachelor party'),
  S('Your dating app bio, but honest'),
];

// {name} is replaced by a player in the room (only when "Questions about us" is on).
export const ZINGER_NAMED = [
  "{name}'s secret talent",
  "The title of {name}'s autobiography",
  'What {name} is really thinking right now',
  "{name}'s superhero name",
  'The first thing {name} would do as president',
  'The worst job for {name}',
  "What {name}'s pet says about them",
  "{name}'s go-to karaoke song",
  "The weirdest thing in {name}'s fridge",
  "{name}'s secret hobby",
  'What {name} would bring to a desert island',
  'A warning label for {name}',
  "{name}'s catchphrase",
  'What {name} does when nobody is watching',
  "The name of {name}'s future boat",
  "{name}'s worst habit",
  'What {name} will be famous for',
  'The reason {name} got kicked out of the zoo',
  "{name}'s famous last words",
  'What {name} spends all their money on',
  "{name}'s villain origin story",
  'What {name} googled this morning',
  "{name}'s theme song",
  "The title of {name}'s cooking show",
  'What {name} would name their pet dragon',
  "{name}'s real job is secretly...",
  "The weirdest rule in {name}'s house",
  S("{name}'s dating profile headline"),
  S('What {name} does at 2 a.m.'),
  S("{name}'s signature cocktail"),
];

// Final round: everyone answers the same prompt.
export const ZINGER_FINALS = [
  'Invent a new holiday and its main tradition',
  'Write the tagline for the movie about this group of friends',
  'The thing this group would get arrested for',
  "Describe your perfect day off in three words",
  'Pitch a terrible new game show',
  'Name a new flavor of ice cream and sell it to us',
  "Write a fortune cookie that's way too specific",
  "The worst possible theme song for this party",
  'Invent a sport we can play in this room right now',
  'Write the first line of the worst novel ever',
  'Describe the afterlife in five words',
  'What the aliens should say when they finally land',
  'The worst possible name for a baby',
  'Invent a new word and tell us what it means',
  "The best thing about being a cardboard box",
  'Your plan if you woke up as a pigeon',
  "Write a one-star review of planet Earth",
  'The motto of your future cult',
  'Describe your ideal pet monster',
  'The new national anthem, first line only',
  S('Write the worst opening line for a wedding speech'),
  S('The real reason this party will be legendary'),
  S('Describe your last relationship as a movie title'),
];

// "Safety jabs" for players who are out of ideas.
export const SAFETY = [
  'Three raccoons in a trench coat',
  'A suspicious amount of mayonnaise',
  'Absolutely nothing, and I mean nothing',
  'Grandma, again',
  'Bees. So many bees.',
  'A sad trombone noise',
  'A wet sock',
  'Moist towelettes',
  'Glitter. Endless glitter.',
  'A haunted toaster',
  'My mortal enemy, Gary',
  'Soup',
  'An emotionally unavailable goose',
  'The ghost of a hot dog',
  'Forty bananas',
  'A strongly worded letter',
  'A dramatic slow clap',
  'Interpretive dance',
  'Tax season',
  'Crocs with socks',
  'A raccoon with a law degree',
  'My uncle Steve',
  'Pure, unfiltered chaos',
  'A single, perfect potato',
  'The audacity',
  'A spork',
  'Feral toddlers',
  'Fifteen pigeons',
  'Expired yogurt',
  'Accidentally replying all',
];
